sudo: false
dist: trusty
language: java

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
  - ~/.m2

env:
  global:
  - secure: elEBSzU7KHyY+tYconN7ISI1OaRq/C3NSviIc62KdeatVdKiRfjFsfJA0sfbDcsQCcW5nNUN8P2Gaatw/ph8WlqnZSb35YhMgQnYu7ssIm1Mpz2qs9lcffOG1RTUG1L6bOvwXxbxjFsCOBmxML9QiFaUNoQZfw6hbMQkkRQxfvPLlt9gL2e1A6y8UnqZCmB7nbJFy/RaBNhpIZqFgh0Z7JqGL2jjMr+OkBqVJlSI6u3VnMr9WYDlg69MUmaWQovHCpe2UuT1wU6YnQAMD2FJCpuTgigyW876ZUsI2T2Z9OMuZm+GANS5zA9C13piNeOvz6Rm1C4ZtNu95CPB0x4GXxmnoT+L6xMCZ5Ba24PrV5lezG5n6+ZEnUjold5pn45wgDS/+3XQPjR4kxxxCnVuD2QdX3TjeYqPe8Fo0rsp7Ad8JfirqiXwHwZOTFiQARsCA2tb0XSWElAuKkw6N3xnejsbD2bbCNTwmgW82pnIXEMADW0uPgf7qGCaAIM/X7sWB1YPmPjjv6qKHRZKbBeX6B/+qNyEjdOhsOHyoh6Ww83xpJrq4dDr2jP8WMQNEUe1j4GMj0CVtWezQr3nHluLe86AcaUjDVUJ4infHAew14djDE9BWxs610sT3wwDoKo+o5sH67jZO8SeRD7Z+g0z7aUChxkMVh9tQBdrfhw6qpc=
  - secure: j9idy7d7Jb9lvi2YVWW66kMEl3jFq+ukf3ndI68oIU1ySpGk9dVPXD+BK7rPf0YPCZRco37DnGLBYqtxDdjVeN9F4EoKGUrYRVcocp5l4qKJFFUCSl4W8VKkq1QOP8ABhfvRIjEaUfNFI5Ps7MZ8eHqvpbFqOd4PhVb+Bbdm2bBxP/wGQcg+361pZylgcNoKc5lltGNV4XrgnBj++8YlRYApHzGaum9UN2t7Wsxl5P6U5gFKL+FCpPUyKbHjVFbJ/awoLnEr+lVDS0FOSInu1x9ENU0V/Cpa0ttkiQ+1oOwVX401CosDUcII20ckf7y4clyiXzsA7GaxfQfv8O7mD6eLJ0hMz5KNGdUY8se0hnHglMIUMqyxNNWR8qkC3Dp+vDDUt9LZk0URslhNK2yV8w4Tfw8xLxB7glYpmYyVhC1LWnyfZlWX70fNJCbwRKfbx2uAyPCxYnS0ajidVwOVYHBXwcs+R/NASibL28//b8oSJwwV2mMM7iDJjrvJmzdeazfc6pqa6IWYcxN05N7gbY5924pVtasH0NmFCUTWEd8y2ULshUSlmNWatunfLJGG2YrFoBeN/rJDfvMpVw2+/0flwCJWHCyBSv2Amz2sei9UDHKwlMe3FKuJC53I9O3xyURE5xYlJaKgd9NRqkvdeGgJZWNYW6h/lFNZeKqMGQE=

before_install:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then source ./travis/non_pull_request_setup.bash; fi'

install:
- travis/install.bash

before_script:
- echo "PR ${TRAVIS_PULL_REQUEST} and TAG '${TRAVIS_TAG}' Branch ${TRAVIS_BRANCH}"

script:
- travis/deploy.bash
- ssh-agent -k || true

after_success:
- echo "Success."

webhooks:
    # Adds Travis CI build notifications to the gitter room
    # yahoo/fili-notifications
    urls:
        - https://webhooks.gitter.im/e/b06234f8aa1b5fe7c24a 
    on_success: change
    on_failure: always
    on_start: never
        
